#! /bin/sh

# File: /etc/init.d/unicorn

### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the unicorn web server
# Description:       starts unicorn
### END INIT INFO

app_user="cv"
DAEMON=/usr/local/bin/unicorn
DAEMON_OPTS="-c /home/$app_user/rails-cv-app/config/unicorn.rb -D"
DAEMON_OPTS="$DAEMON_OPTS -E production" #Switches to production environment
NAME=unicorn
DESC="Unicorn app for research subdomain of YOUR_SERVER_FQDN"
PID=/home/$app_user/rails-cv-app/shared/pids/unicorn.pid

case "$1" in
  start)
    echo -n "Starting $DESC: "
    $DAEMON $DAEMON_OPTS
    echo "$NAME."
    ;;
  status)
    echo "PID: `cat $PID`"
    ;;
  stop)
    echo -n "Stopping $DESC: "
        kill -QUIT `cat $PID`
    echo "$NAME."
    ;;
  restart)
    echo -n "Restarting $DESC: "
        kill -QUIT `cat $PID`
    sleep 1
    $DAEMON $DAEMON_OPTS
    echo "$NAME."
    ;;
  reload)
        echo -n "Reloading $DESC configuration: "
        kill -HUP `cat $PID`
        echo "$NAME."
        ;;
  *)
    echo "Usage: $NAME {start|status|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
