# The present YAML file is loaded as Settings in config/initializers/load_config.rb

name: "Bertrand Caron"

# Title of the website, as displayed in the navbar
page-title: "Academic Curriculum Vitae"

# CV Title
cv-title: "Future PhD Student"

# Alternate CV title displayed when hovering over CV title. Comment out to disable this effect.
cv-title-alt: "Web Developer ?"

# Disclaimer displayed at the bottom of the page, in the footer
disclaimer: "Powered by <a href='http://bcaron.me' >Myself</a>"  

# Email receiving the messages sent via the Contact Form
email: admin@bcaron.me

social-media:
  github: bertrand-caron # Github username
  stack-overflow-id: 1680996 # Stack overflow ID; your profile link is http://stackoverflow.com/users/{StackOverflow_ID}/{StackOverflow_UserName}
  stack-overflow-name: bertrand-caron # Stack overflow Name; your profile link is http://stackoverflow.com/users/{StackOverflow_ID}/{StackOverflow_Name}

mobile-phone: "+(33) 6 62 04 28 09"
address: "6 Rue Charles Dubois, 80000 Amiens, France"
infos: "22 years old"

domain-name: "cv.bcaron.me"

# Display the 'Fork on Github' footer
display-footer: true
